import React from 'react'

export default function About() {
  return (
    <div className='About'>
      <h1>About</h1>
      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Odio impedit veritatis cum optio deserunt aliquid consequuntur, odit animi laboriosam possimus tempore rerum nostrum adipisci delectus repellendus voluptate doloribus quidem. Quidem esse hic, voluptas, nisi dolorem vitae sequi itaque eius laudantium corrupti excepturi pariatur corporis, autem quae earum optio consectetur fuga maiores odit eos sunt molestiae recusandae! Molestiae consequuntur sed voluptate officia dicta dolorem vero aut reiciendis tempora sapiente ut rem voluptatibus placeat, commodi modi laborum? Reprehenderit adipisci nihil facilis dolor quas ipsa dignissimos, ducimus voluptates illum labore! Ipsum molestias dolorem reiciendis praesentium debitis, soluta vitae cum ab, corrupti quae nobis ut, quod eius dicta sapiente ad esse. Quia nemo excepturi aperiam, officiis nisi ab quis mollitia illo quisquam a labore, delectus facilis! Facilis qui omnis aut veritatis! Veritatis architecto magnam quam corrupti sunt error quaerat nostrum est hic, sint ratione ad corporis. Aliquam provident quibusdam illum architecto atque vel libero molestias officia, ipsa maiores, culpa eos aut officiis! Rerum, deleniti. Asperiores voluptatem libero odit nam corrupti vel laboriosam quam minima? Iusto, quisquam animi eum odit eos earum perspiciatis officiis sint ut, ex impedit quasi aut inventore molestias necessitatibus in delectus aperiam libero maxime. Maxime molestias id vitae, fugit nisi ratione. Optio commodi repudiandae cum voluptatibus excepturi quas voluptas, accusantium vitae fuga illo nulla, labore iure maiores minima cumque! Enim rem id eveniet dolorem beatae odit illo in eligendi placeat magni praesentium possimus voluptatem aperiam, quaerat nisi voluptate amet mollitia ipsum perferendis corporis laboriosam ad nam. Vitae pariatur quibusdam atque doloribus unde. Quaerat quibusdam debitis cumque dolor iste necessitatibus quos nam impedit tempore reprehenderit. Fuga vel, error officia necessitatibus quasi quod modi voluptatibus, eaque sequi, suscipit voluptatem assumenda quam dicta inventore ut nisi quia sapiente. Nobis aut culpa exercitationem? Reiciendis nemo aliquid eius illo blanditiis praesentium quae aperiam vitae? Voluptatem, quaerat?</p>
    </div>
  )
}
